name: Static analysis

on: [push, pull_request]

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      # Checkout our code
    - uses: actions/checkout@v2
    # Setup python 3.8
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    # Setup deps
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
    - name: Lint with pylint
      run: |
        pylint --rcfile=.pylintrc hnet
        pylint --rcfile=.pylintrc tests
    - name: Lint with flake8
      run: |
        flake8 hnet --exit-zero
        flake8 tests --exit-zero
    - name: Lint with black
      run: |
        black -l 79 --check hnet
        black -l 79 --check tests
    - name: Type check with mypy
      run: |
        mypy hnet
        mypy tests