name: Run tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout our code
    - uses: actions/checkout@v2
    # Setup python 3.8
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    # Setup deps
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
    - name: Tests with pytest
      run: |
        coverage run --source hnet -m pytest tests/
        coverage report --show-missing